name: jagu_meet
description: Video conferencing app developed by Jagadish Prasad Pattanaik 2020.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 8.2.0+4025

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  jitsi_meet: ^4.0.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.5.0
  cloud_firestore: ^2.5.4
  google_sign_in: ^5.0.3
  google_mobile_ads: ^0.13.3
  share: ^2.0.1
  url_launcher: ^6.0.7
  rate_my_app: ^1.1.0+1
  shared_preferences: ^2.0.7
  firebase_dynamic_links: ^2.0.8
  provider: ^6.0.0
  random_string: ^2.1.0
  fluttertoast: ^8.0.8
  package_info: ^2.0.0
  date_time_picker: ^2.0.0
  carousel_slider: ^4.0.0
  quick_actions: ^0.6.0+6
  cached_network_image: ^3.0.0
  device_info: ^2.0.1
  dots_indicator: ^2.0.0
  connectivity: ^3.0.4
  badges: ^2.0.1
  overlay_support: ^1.2.1
  webview_flutter: ^2.0.12
  flutter_offline: ^2.0.0
  in_app_review: ^2.0.2
  in_app_update: ^2.0.0
  timeago: ^3.0.2
  permission_handler: ^8.1.3
  pull_to_refresh: ^2.0.0
  responsive_builder: ^0.4.1
  url_strategy: ^0.2.0
  font_awesome_flutter: ^9.0.0
  universal_platform: ^1.0.0+1
  sign_button: ^2.0.1
  firebase_messaging: ^10.0.5
  flutter_local_notifications: ^9.0.1
  flutter_native_timezone: ^2.0.0
  #mediation_test: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/images/

  uses-material-design: true

 # fonts:
 #   - family: OpenSans
 #     fonts:
  #      - asset: assets/fonts/OpenSans-Regular.ttf
  #  - family: Poppins
   #   fonts:
   #     - asset: assets/fonts/Poppins/Poppins-Regular.ttf
   #     - asset: assets/fonts/Poppins/Poppins-Medium.ttf
  #        weight: 600
   #     - asset: assets/fonts/Poppins/Poppins-Bold.ttf
   #       weight: 700

