name: jagu_meet
description: Video conferencing app developed by Jagadish Prasad Pattanaik 2020.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+4003

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  jitsi_meet: ^2.0.0
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  google_sign_in: ^4.5.5
  #font_awesome_flutter: ^8.10.1
  share: ^0.6.5+4
  url_launcher: ^5.7.10
  rate_my_app: ^0.7.2
  shared_preferences: 0.5.12+4
  firebase_dynamic_links: ^0.6.3
  provider: ^4.3.2+3
  random_string: ^2.1.0
  sqflite: ^1.3.2+1
  path_provider: ^1.6.24
  path: ^1.7.0
  fluttertoast: ^7.1.5
  package_info: ^0.4.3
  date_time_picker: ^1.1.0
  carousel_slider: ^2.3.1
  image_gallery_saver: ^1.6.6
  quick_actions: ^0.4.0+10
  cached_network_image: ^2.4.1
  device_info: ^1.0.0
  dots_indicator: ^1.2.0
  argon_buttons_flutter: ^1.0.6
  flutter_spinkit: ^4.1.2+1
  connectivity: ^2.0.2
  badges: ^1.1.6
  overlay_support: ^1.0.5
  webview_flutter: ^1.0.7
  flutter_offline: ^0.3.0
  in_app_review: ^1.0.4
  in_app_update: ^1.1.14
  pull_to_refresh: ^1.6.3
  timeago: ^2.0.29

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/schedule.png
    - assets//images/clock.png
    - assets//images/chat.jpg
    - assets/images/startjoin.jpg
    - assets/images/stay.jpg
    - assets/images/unlimited.jpg
    - assets/images/secured.jpg
    - assets/images/multiple.jpg
    - assets/images/lowmode.jpg
    - assets/images/youtube.jpg
    - assets/images/waiting.jpg
    - assets/images/password.jpg
    - assets/images/search.png

  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

